- name: variables
  hosts: [web]
  become: yes
  var:
   name1: "zara"
   name2: "sonu"
  tasks:
   - name: override variables
     ansible.builtin.debug:
      msg: "hi my name is {{name1}}"
            "helo my name is {{name2}}"

  - name: variables
    hosts: [local hosts]
    var:
     name1: "devops" 
  tasks:
   - name: printing msgs
     ansible.builtin.debug:
      msg: "hi my name is {{name1}}"
            

            
            
