- name: variables declaration
  hosts: [web]
  var: # variable declaration
   name1: "zara"
  tasks:
   - name: override information print
     vars: # task level variables
       name: "zara"
     ansible.builtin.debug:
      msg: " hi my name is "{{name1}}.""
          

- name: print information
  ansible.builtin.debug:
    msg: "hi,my name is {{name1}}"           

  

            
            
