- name: variables
  hosts: [web]
  become: yes
  var: # variable declaration
   name1: "zara"
   name2: "sonu"
  tasks:
   - name: override variables
     vars: #override information
      name: "zara"
     ansible.builtin.debug:
      msg: " hi my name is {{name1}}"
           " helo my name is {{name2}}"

  

            
            
