- name: print information 
  hosts: [local host]
  vars:  
   name1: "zara"
  tasks:
    - name: print information
      vars: #tasks
       name1: "zara"
       ansible.builtin.debug:
        msg: " hi my name is {{name1}}"

   
    - name: print information
      ansible.builtin.debug:
        msg: "my name is {{name1}}"
      
          

-
  

            
            
