- name: print information 
  hosts: localhost
  vars:  
   Person1: "zara"
   Trainer: "shiva"
  tasks:
    - name: print information
      vars: #tasks
       Person1: "zara"
      ansible.builtin.debug:
        msg: " hi my name is {{Person1}}" my trainer is {{Trainer}}

   
    - name: print information
      ansible.builtin.debug:
        msg: "my name is {{Person1}}" my trainer is {{Trainer}}
      
          

-
  

            
            
