- name: print information 
  hosts: localhost
  vars:  
   Person1: "zara"
   Trainer: "shiva"
  tasks:
    - name: information
      var: #task level information
       Person1: "sha"
       ansible.builtin.debug:
        msg: " hi my name is {{Person1}}, my trainer is {{Trainer}}."

   
    - name: trainer information
      ansible.builtin.debug:
        msg: "my name is {{Person1}}, my trainer is {{Trainer}}."
      
          



  

            
            
