- name: variables declaration
  hosts: [web]
  var: # variable declaration
   name1: "zara"
  tasks:
    - name: print information
      vars: # declaration of variables
       name: "zara"
     ansible.builtin.debug:
      msg: " hi my name is {{name1}}"

   

      
          

-
  

            
            
