- name: variables
  hosts: localhost
  vars:  
   Person1: "zara"
   Trainer: "shiva"
  tasks:
    - name: print override information
      vars: #task level information
       Person1: "shabu"
      ansible.builtin.debug:
        msg: " hi my name is {{Person1}}, my trainer is {{Trainer}}."

   
    - name: print information
      ansible.builtin.debug:
        msg: "my name is {{Person1}}, my trainer is {{Trainer}}."
      
          
  

            
            
