- name: variables 
  hosts: web
  become: yes
  vars: #variable declaration 
   course: "devops"
   name: "shivareddy"
   time: "100hrs"
  tasks:
    - name: printing msgs
      ansible.builtin.debug:
       msg: "hi,im learning {{course}},my trainer is {{name}},duration of course is {{time}}"
