- name: variables from files
  hosts: localhost
  vars_files:
   - vars.yaml
  tasks:
   - name: print ovverride information
     ansible.builtin.debug:
      msg: "hi, i am learning {{course}}, from trainer {{Trainer}},duration {{time}}."